### ISSUE TITLE
Currently seeing bracketed names on page title area

### ISSUE THREAD

**Issue by nogginfuel** [richi/yellow-plugin-faq#1]
I'm currently seeing the page title as [faqFilter] [faqListTitle] when the page loads. I'm assuming it should just say FAQ, however, I didn't see an example of what it should look like when properly installed. Is that area supposed to be a menu or a drop down of some kind? If you want to see it yourself, please visit, http://cardonic.co/faq/

**Comment by richi** [comment]
You need to complete the step 8 of the installation instructions:

Add the keys FaqFilter: FAQ, FaqListTitle: by Title, FaqListModified: by Date, FaqTag: Tags: to your system/config/language-*.ini files.

**Comment by nogginfuel** [comment]
Thanks, I somehow wasn't paying close enough attention. I put those in the main ".ini" instead of the language specific file. I also thought "FaqTag: Tags:" were 2 separate keys not 2 parts of the same key. Everything is cleared up now. Thanks for your response.
