### ISSUE TITLE
Great work + some feedback

### ISSUE THREAD

**Issue by markseuffert** [richi/yellow-plugin-faq#2]
Hi Richi,

great to see so many plugins, looking forward to see what else you create. I didn't have your email address, hope it's okay to open an Github issue with some feedback:
- plugins can add new language files, for example `system/config/language-something-en.ini`
- how about naming repositories `yellow-something` or `yellow-type-something`?
- please keep attribution/license if you're using plugin code from main repositories
- let me know if anything is missing in the Yellow API 

Happy coding and greetings from Sweden, Mark :smile:

**Comment by richi** [comment]
> hope it's okay to open an Github issue with some feedback

Absolutely!

I hope my changes fit. If not, please let me know :+1:

**Comment by markseuffert** [comment]
Thanks a lot, appreciate it. 

You are not listed as contributor in the Yellow repositories like everyone else. Do you know why?

**Comment by richi** [comment]
Probably because I did not have an email address in my github account or my commits. Tried to avoid that for more than 5 years, but now I have given up :-)

https://github.com/richi/

**Comment by markseuffert** [comment]
Ah, good to know. Looking forward to next pull request. :)
